### ISSUE TITLE
Several Questions

### ISSUE THREAD

**Issue by chase-watts** [DunnCreativeSS/Redirect.comBuyingAndZeroPark.comSelling#1]
Hi there

A few quick questions for you:

1.  The minimum bid on Redirect is $0.20 for the standard feed, but for RON it's $0.10.  Where in the script should I update it to drop the bid as low as $0.10 instead of $0.20?  I see .2 in several places, so I wasn't sure which needed to be changed.

2.  Do you run the script on a cron job?  If so, how often do you have it run to update the campaigns?

3.  Based on the amount of campaigns you have, I'm guessing that you programmatically created them on Redirect.  Do you happen to have the script that does that?

Thanks for your time and have a great day!

- Chase

**Comment by dumblob** [comment]
@chase-watts did you find satisfying answers to your questions? I'm also asking them myself so feel free to let me know what did you find out.
